# docker-compose version
version: '2'
# containers
services:
  nginx:
    # the latest stable nginx image
    image: nginx:latest
    ports:
      - "8090:8080"
      - "4445:4443"
    user: ${ALEC_UID}
    depends_on:
      - alec
    # mount directories from:to
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx:/etc/nginx/conf.d
      - ./app:/var/www
      - ./../alec-logs:/var/log/nginx
      - ./docker/nginx/proxy/certs:/etc/nginx/certs
    # link nginx container to php container
    links:
      - alec
    networks:
      - default
  alec:
    # path to our PHP image that will be built
    build: ./docker/php${PHP_IMAGE_ALTER}
    # mount project's dir
    user: ${ALEC_UID}
    volumes:
      - ./app:/var/www
    depends_on:
      - alec_mysql
    environment:
      XDEBUG_CONFIG: client_host=${CLIENT_HOST} client_port=9003
    image: alec
    command: bash -c "XDEBUG_CONFIG= composer install && php /var/www/console/yii.php migrate --interactive=0 && php-fpm"
    networks:
      - db_net_alec
      - default
  alec_mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --sort_buffer_size=20M --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3336:3306"
    user: ${ALEC_UID}
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: alec2
#      MYSQL_USER: sandbox_user
#      MYSQL_PASSWORD: passpass
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./../alec-mysql:/var/lib/mysql
      - ./docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_net_alec
  alec_stat_api:
    build: ./python-app
    volumes:
      - ./python-app/app:/code/app
    container_name: alec_metrics-api
    environment:
      PORT: 8800
    ports:
      - '8800:80'
    restart: "no"

networks:
  db_net_alec:
    external:
      name: db_net_alec
  default:
    external: false
